import json,pathlib,html
x=json.load(open('public/research/evaluation-v24.json'));ss=x['summaries']
labels={'strongChord':'拍頭のコードトーン','turn':'方向反転','third':'3・4半音の進行','step':'同音・1〜2半音の進行','stepRun':'同方向の順次進行3連続','nonchordResolve':'非和声音→次音の和声音へ順次解決','motifRepeat':'音程・リズム3連続の反復','endOnBeat':'フレーズ終音の拍頭発音','span':'使用音域幅（半音）','density':'1拍あたりの発音数'}
def val(k,s,iqr=False):
 d=s[k];f=lambda v:'—' if v is None else f'{v:.2f}' if k in ['span','density'] else f'{v*100:.1f}%'
 return f(d['median'])+(f" [{f(d['q25'])}–{f(d['q75'])}]" if iqr else '')
table=''.join('<tr><th>'+label+'</th>'+''.join('<td>'+val(k,ss[v],v in ['train','reference'])+'</td>' for v in ['train','reference','v23','v24'])+'</tr>' for k,label in labels.items())
tempo=''.join(f"<tr><td>{g['source']}</td><td>{g['bars']}</td><td>{g['tempo']}</td><td>{g['windows']}</td><td>{g.get('solos','—')}</td><td>{val('strongChord',g['summary'])}</td><td>{val('turn',g['summary'])}</td></tr>" for g in x['groups'])
worst=sorted([r for r in x['rows'] if r['version']=='v24'],key=lambda r:r['motifRepeat'],reverse=True)[:5]
wtable=''.join(f"<tr><td>{r['preset']}</td><td>{r['bpm']}</td><td>{r['seed']}</td><td>{100*r['motifRepeat']:.1f}%</td></tr>" for r in worst)
pathlib.Path('public/research/review-v24.html').write_text('''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ビバップ生成の厳格検証 — 2.4</title><style>body{max-width:920px;margin:30px auto;padding:0 18px;background:#faf9f4;color:#242821;font:15px/1.8 system-ui}h1{font-size:23px}h2{font-size:18px;margin-top:30px}a{color:inherit}button,select{font:inherit;padding:8px;max-width:100%;background:transparent;border:1px solid #aaa;margin:4px 0}td,th{padding:7px;text-align:left;border-bottom:1px solid #ccc}table{border-collapse:collapse;font-size:13px;width:100%}.scroll{overflow-x:auto}code{font-size:12px}summary{cursor:pointer}</style><body data-comparison="v24"><a href="../">← 練習に戻る</a><h1>ビバップとしての偏りを検証する — 2.4</h1><p>2026-10-05。結論：2.3には拍頭をコードトーンに寄せすぎる傾向と、頻繁な方向反転がありました。2.4はこの2点を緩和しましたが、本物のビバップと同等の自然さを証明したものではありません。専門家の盲検聴取評価は未実施です。</p>
<h2>比較の仕方</h2><p>Weimar Jazz DatabaseのBEBOP分類56ソロ。43ソロを調整用、13ソロを参照用に分離。13ソロは過去にも結果を見ているため「未見のテスト」とは呼びません。4/8小節の完全な窓・6音以上・4/4・細かい装飾音を除外し、同じ定義で比較します。音程と接続は同一フレーズ内・発音間隔1拍以下。拍頭＝四分音符の整数拍。和声は解釈可能な基本コードだけ。和声の違う曲、奏者、楽器、窓の長さの割合は一致していません。数値の差をそのまま品質差とは解釈できません。</p><p>調整にはシード1001〜1030の720例を使用。最終比較は別の2001〜2030、6進行×80/140/200/280 BPMで各版720例、計1,440例。実音C4〜C6。4小節窓と8小節窓は互いに重なるため、窓数は独立な標本数ではありません。全結果にはテンポ・小節数・奏者・ソロ単位の集計も含めています。</p>
<h2>研究から何を採用したか</h2><ul><li><a href="https://mtosmt.org/issues/mto.12.18.3/mto.12.18.3.love.html">Love (2012)</a>：Parkerのブルースでは、和声をまたぐ旋律の道筋とフレーズ配置を区別する。途中の各拍を着地と同じ強さで拘束しない設計へ。ただし研究対象はParkerのブルースで、全ビバップへの普遍則ではない。</li><li><a href="https://ai.stanford.edu/~kdtang/papers/cmj10-jazzgrammar.pdf">Gillick・Tang・Keller (2010), Machine Learning of Jazz Grammars</a>：リズム・輪郭・和声上の音の役割を分ける文法。半音アプローチ、着地、モチーフ応答の役割は維持し、和音適合率だけを最大化しない。</li><li><a href="https://transactions.ismir.net/articles/10.5334/tismir.87">Frieler・Zaddach (2022)</a>：単純な音高・リズム統計では全体の質を測れず、演奏表現が評価に影響する。今回も分布比較を補助診断とし、同じ音色・伴奏・タイミングによるA/Bを用意する。同論文もWJazzDを使い、独立コーパスでの追試ではない。</li></ul>
<h2>実装への反映</h2><ul><li>フレーズ内部のガイドトーン・コードトーンの加点を弱め、短い経過音を拍頭にも許す。長く伸ばす不安定音への抑制と、ii–V–Iの着地は維持。</li><li>短い11thの経過音と、長く伸ばす11thを区別。半音アプローチを後付けする頻度を34%から18%へ下げ、すでにある解決や囲みを保護。</li><li>上・下・上のような反転が連続する候補に小さな減点。単発の方向転換、囲み、跳躍後の回復は引き続き許す。</li></ul><p>これらの数値は文献に記された最適値ではなく、43ソロとの開発比較に基づく設計値です。生成のシード・モデル版を保持し、音域・タイミング・伴奏・保存済みフレーズの音符は変更しません。</p>
<h2>最終比較</h2><p>各窓／生成例の中央値。参照資料は [25–75パーセンタイル] も表示。信頼区間ではありません。</p><div class="scroll"><table><tr><th>測定</th><th>調整用43ソロ</th><th>既参照13ソロ</th><th>2.3</th><th>2.4</th></tr>'''+table+'''</table></div>
<p>順次進行と短い反復は増えました。大跳躍の少なさ、限られた34種のリズム素材、解決点をガイドトーンへ寄せる設計、拍頭で終わりやすい癖も残っています。参照の中央値へ全部を合わせることを目標にせず、次の聴取評価で確認すべき弱点として残します。</p>
<details><summary>テンポ別・小節数別の件数と結果</summary><p>train＝調整用、reference＝既参照13ソロ。各帯域の奏者数・全指標・ばらつきはJSON参照。低速はバラードも含み、テンポだけで同じ奏法とはみなしません。</p><div class="scroll"><table><tr><th>資料</th><th>小節</th><th>BPM帯</th><th>窓／例</th><th>ソロ</th><th>拍頭コード音</th><th>方向反転</th></tr>'''+tempo+'''</table></div></details>
<h2>良い例だけを選ばない聴き比べ</h2><p>長調・短調・循環ii–V・リズムチェンジの4進行×4テンポ。シード2017で固定し、出来栄えによる除外はしていません。旧版＝2.3、新版＝2.4。音色・伴奏・タイミング・基本の強弱を共通にし、比較ごとにA/Bの割当てを変えています。版はボタンで確認できます。無作為な被験者実験ではありません。</p><select id="example" aria-label="進行とテンポ"></select><div><button id="A">Aを再生</button> <button id="B">Bを再生</button> <button id="stop">停止</button></div><p id="result" role="status">再生を押してください</p><button id="reveal">版を表示</button><span id="answer"></span><p>「ビバップの語法として納得できるか」「2小節をまたいで線がつながるか」「反復が音楽的に働くか」「楽器で吹いて覚えたいか」を別々に確かめてください。今回は専門家による採点や、聴感の改善を確認したという主張はしていません。</p>
<details><summary>弱点を含む例：反復の多かった5例</summary><p>3連続の音程・発音間隔が同一窓内で複数回現れた割合の上位。低品質ランキングではなく、機械的反復の点検候補。進行番号は0＝長調ii–V–I、1＝短調、2＝turnaround、3＝ii–V cycle、4＝blues、5＝rhythm changes。メイン画面の研究シートからシードを指定できます。</p><table><tr><th>進行</th><th>BPM</th><th>シード</th><th>反復割合</th></tr>'''+wtable+'''</table></details>
<h2>追加データとタイム感</h2><p>既に収集したJazz Trio DatabaseとPiJAMAの集計も確認しました。ただし自動採譜した多声音楽の最高音列はビバップの単旋律の正解ではないため、旋律の目標値に混ぜていません。PiJAMAから微細なタイミングを推定せず、今回タイミングは変更していません。独立資料の件数・ライセンス・除外条件は<a href="review-v2.html">先行調査</a>、派生集計は今回のJSONに記載しています。</p>
<h2>再現と検証</h2><p>Node 24 / Python標準ライブラリ。元DBは公開ファイルに含めません。<a href="audit_reference.py">参照資料の抽出</a> → <a href="evaluate_v24.ts">最終評価</a>（<a href="audit_metrics.ts">共通測定</a>） → report_v24.py。ソース一式には固定した2.3と2.4を含めます。</p><pre><code>python3 research/audit_reference.py
node research/evaluate_v24.ts
python3 research/report_v24.py
pnpm test
pnpm typecheck
pnpm build</code></pre><p><a href="evaluation-v24.json">全結果・奏者別集計・定義・限界</a> / <a href="comparison-v24.json">固定比較例</a> / <a href="review-v23.html">前版</a></p><p>20件の機能・回帰テストを確認。音域、12キー、長短調、変化和音、半音解決、拍数、実際の譜面用音価、再生音数、重複発音、掛け合い・無限演奏を含みます。iPhone実機・専門家の盲検聴取は未確認。数値的な改善と「本物のビバップとして十分」は区別します。</p><p>WJazzD派生集計は<a href="NOTICE.txt">ODbL / DbCL</a>。録音・採譜・元MIDIの転載はありません。</p><script type="module" src="listen-v2.js"></script></body></html>''')
